const titles = [
    "get an extreme ache when thinking about how much you love animals?",
    "HATE wishes?",
    "think that Texas Roadhouse rolls aren\'t as good as everyone says they are?",
    "share a bday with me today?",
    "add ketchup to any food they have on sight except pizza?",
    "think constantly? I can’t catch a break",
    "see the time and round up?",
    "not listen to songs that are longer than 4 minutes??",
    "make themselves sneeze because it feels good",
    "have once in a lifetime events in their life or have done things in their life that they feel define them years later? Good or bad?",
    "not like long sleeve tshirts without a cuff?",
    "love dry cornbread? Lol",
    "feel distressed about sexuality?",
    "just seem to not be able to memorize certain things?",
    "miss laughing so hard tears come out?",
    "feel too shy to curse?",
    "lowkey hope to be rejected because you don’t think that person/job is for you anyway…",
    "like being CC\'ed on emails when you don\'t need to be?",
    "just want to experience true humanity again? So much inhumanity.",
    "just look at people and think how can they be soooooo emotionally non-intelligent?",
    "prefer a quick forehead kiss?",
    "become naked in their dreams sometimes",
    "only have friends from their adult years? No childhood friends?",
    "get nervous being out in public anymore?",
    "get like bad fatigue BEFORE getting sick with something like the cold or flu or like sinus problems?",
    "save the best bite of their meal for last just to get too full to finish it?",
    "else rush/stress to relax ?",
    "hate the feeling of never being enough?",
    "have a V active, negative, vivid imagination?",
    "put a pillow between your legs when you sleep?",
    "feel like they aren\'t enough into anything really and feel guilty about it? Like do you feel like your interests are too unique?",
    "Hate how videos meant for kids automatically disables the comment section?",
    "shower in complete darkness?",
    "get a really loud belly when in a quiet room (waiting room, classroom...) with other people?",
    "hate the social expectations of being an adult?",
    "\'s brain loop to the previous/same line when reading a page of text?",
    "get insecure and anxious when alone on the computer, but feel more confident and secure when out and doing things?",
    "get upset when they post on this subreddit hoping that people would relate and no one relates to them 😭",
    "listen but not LISTEN?",
    "stalk their crush on social media out of habit? I’m not even interested anymore but I’m so used to doing this.",
    "ever feel guilty when someone asks you if you speak another language and you don’t?",
    "feels happy today?",
    "not get “SNL”?",
    "feel awkward showing any sort of affection to their parents?",
    "sound harsh not because you’re harsh but you thought that’s how people expect of you?",
    "got put in a special program as a kid to learn how to catch balls ?",
    "get a sympathy sensation when seeing someone get hurt on TV?",
    "feel bad tearing off a calendar page for their diary cuz it’s probably someone’s birthday?",
    "have an \"ugly sneeze\"?",
    "feel like exercise is for masochists?",
    "not have a third place?",
    "walk in heels like they\'re on a balance beam?",
    "not have any photos of themselves growing up?",
    "have negative associations with certain alarm sounds?",
    "see the word \"union\" and start to read it as \"onion\"?",
    "have deep emotional connections with songs?",
    "find it easier to not drink (alcohol) if they also don\'t eat?",
    "discard the first pieces of a roll of TP when using a public restroom?",
    "think they made progress in being more confident and having thicker skin but then something happened and you realise that nothings changed?",
    "hate the noises their phone makes so they always have it on vibrate?",
    "sing \"My butthole\'s on fire\" to the song \"That girl is on fire\"?",
    "find that they can\'t really enjoy any storytelling media without being hyperaware of its flaws?",
    "feel like you are running out of time to do the things you want to do?",
    "get hyper aware of singers breathing while singing that it ruins the song",
    "use “god bless” as just another way to say “i agree”",
    "Get a crazy image slideshow when waking up?",
    "grow up half poor and half rich?",
    "wish there was a browser extension that would block content based you giving it the finger?",
    "think that US doctors have lost their bedside manner?",
    "feel intense rage over small occurrences?",
    "as an adult still have a snack cupboard/drawer?",
    "have a parent who still acts like you don’t know how to drive whenever you take them somewhere?",
    "don’t care what people do with the gift you gave someone?",
    "\"tune out\" their feelings?",
    "heavily prefer youtubers over streamers?",
    "add already done items to the to-do list just to check them off?",
    "have an attachment to scents ?",
    "drink raw milk?",
    "find themselves holding onto the bed rail when laying in bed?",
    "feel like they don’t know how to burp",
    "have their temperature be dependent on how much they’ve eaten?",
    "imagine different accents for their pets if they could talk?",
    "look at a new product and know it’s to make more money?",
    "Get worried that they committed a crime a forgot about it?",
    "have no idea how they would \"Gaslight\" someone",
    "need pressure on their hands to fall asleep?",
    "have an OCD about their phone cases?",
    "absolutely love thinking about things that go over their head?",
    "with more than one design of silverware in their drawer have a design that they prefer to use?",
    "struggle to keep their attention on a book",
    "think that days pass by too fast?",
    "Feel Overwhelmed By Their Own Emotions",
    "feel like they ruin store items once they’ve been touched",
    "Feel weird buying things to sit in a drawer unused?",
    "had a psychosis so bad that they imagine themselves getting beaten up by an invisible entity?",
    "remember those “ring” tones where you could make people listen to songs while they called you?",
    "get uncomfortable agreeing with someone because they feel like they’re “copying” them, even though you truly agree with them?",
    "struggle to read textbooks?",
    "when drinking from a wine or champagne glass get the urge to bite it?",
    "just be looking at memes at your phone and laugh at the worst time possible?",
    "correct their friends grammar through text?",
    "really like their parents (or parent)?",
    "just go feral for the smell of gasoline",
    "hate when you get back from getting food and someone says something like “thanks for letting me know you were getting food! I would’ve placed an order!”",
    "assume that Midwest folks take stanker sh*ts?",
    "get kicked out from pubs for having big pupils?",
    "rake your carpet?",
    "get disheartened when seeing victim blaming on social media?",
    "have an obsession with wing dust seasoning or steak seasoning?",
    "have a different \"main\" handwriting every few years (or every big new \"phase\" of their lives), unintentionally?",
    "Randomly Get Malaise?",
    "taste ‘hidden’ flavours in food items unrelated to them?",
    "Not have anyone who picks you over anyone/anything else?",
    "love love sooooo much, yet fear that you might never find it?",
    "fantasize about having elasticity superpowers when you\'re laying down and don\'t feel like getting up?",
    "feel like food taste better in a restaurant vs take out.",
    "not want any friends/social connection?",
    "feel like group female friendships aren’t worth it?",
    "feel like they\'re in trouble when legally buying alcohol and getting IDed?",
    "watch YouTube while taking a shower?",
    "turn the faucet off when brushing their teeth to conserve water, but then turn it back on after a minute and continue brushing?",
    "get weirdly competitive about how fast you can clean your entire house?",
    "like to put in earplugs in a silent room or house just to hear their own heartbeat?",
    "have dark circles they\'ve had since childhood, even infancy?",
    "have no life outside of work?",
    "rip out their hair while asleep?",
    "get uncontrollably aggressive without a reason as a person with autism?",
    "hate the end of new Superman",
    "fill out online job applications for bosses and coworkers they hate?",
    "not remember yesterdays or day old conversations.",
    "think being a prepper would be fun? Not because you believe it will be necessary but almost like role playing the idea and having it all ready to go seems like a fun hobby?",
    "type out replies and then discard before sending?",
    "not find their own race/ethnicity attractive because it feels a bit too close to family/friends?",
    "Lose Motivation for Work the week Before Vacation",
    "eat something unhealthy and then feel MUCH better after pooping the next day?",
    "feel extremely out of touch because you refuse to use TikTok?",
    "HATE when people start clapping to the beat of a song?",
    "absolutely hate early fall?",
    "feel the urge to lay on the floor and just stay there?",
    "think walking on legos really isn’t that bad?",
    "forget how to swallow?",
    "feel hypersensitive sometimes to small dips in the road?",
    "feel drunk or euphoric after consuming large amounts of sugar",
    "just feel like doing a backflip at the most random times??",
    "clean their plunger or toilet brush?",
    "NOT feel like time flies?",
    "try to fly in their dreams by flapping their arms up and down wildly? In my dreams, it works, I achieve liftoff",
    "fold their gum as they chew it?",
    "feel like they are over this?",
    "get extremely annoyed at people who approach you only to \"help\"?",
    "hear words like you dont know english?",
    "not want to date someone who would be interested in dating them?",
    "drop a book if it\'s just been too long since they last picked it up?",
    "notice how a single scene in a TV show or movie is often obviously shot at different times of day?",
    "feel okay about their body when looking in the mirror, but are disgusted by pictures of your body?",
    "put dandruff shampoo on their eyebrows?",
    "like lemony things that are so tart and lemony that you feel it in your jaw and all the way up to your ears? 🍋🍋🍋",
    "- men in their 70s think \"what am I going to do with the next 15 to 20 years of my life?",
    "feel like they want to be able to listen to all the podcasts for FOMO?",
    "hate to travel abroad?",
    "not get any rest from sleep?",
    "randomly remember lyrics or quotes with no context?",
    "feel like their SSD hard-drive of life experience is full and can\'t take any more photos?",
    "think transit time and car time are 100% different?",
    "sleep with their closets wide open?",
    "think people who post videos of dances on fb and TikTok are imbeciles?",
    "not know that you can use a volume button on a smart phone as a shutter button to take a picture?",
    "wish they had an option on their internet browser, so they could just enter a name and it would never appear on your computer again? For me, it would be Taylor Swift, just *poof* be gone, no need to hear of her romances, her songs, her engagement. her anything. Who would your\'s be?",
    "feel like that the current dating pool for the early-mid 20s being bad as hell is a global phenomenon?",
    "think to themselves “I want to go home” when they’re already home?",
    "know exactly where something is when they loose it?",
    "feel like if you\'ve memorized anything that\'s not sports statistics, you get labeled as a nerd or autistic?",
    "think that movie trailers ruin a film ?",
    "feel this way?",
    "refuse to call their parents Dad and Mom when addressing them?",
    "Only have headaches in the back of the head?",
    "hate sleep?",
    "munch on salad greens without dressing?",
    "have death anxiety as you fall asleep?",
    "feel like it’s getting harder to fake being nice and pleasant?",
    "get mildly disappointed when the only fruit gushers in the variety pack left are the single flavour strawberry one?",
    "hate the feel of moving air on them?",
    "zone out during class only thinking about negative things?",
    "feel like they don\'t belong around either gender?",
    "get disoriented and forget the part of the day?",
    "feel restricted when wearing gloves?",
    "have years upon years of journals that you’ve written in?",
    "have multiple on going projects?",
    "ever flex through the pain...",
    "feel so relieved that they’ve passed their driving test",
    "hate going back to work and being around people again after the summer off?",
    "feel uncomfortable liking a real person?",
    "get mini panic attacks until they wipe or delete their social media?",
    "still get a little embarrassed about buying toilet paper?",
    "feel like their empathy or genuineness is fake?",
    "avoid joining webconferences unless >2 others are already present, to avoid small talk?",
    "think staying in a psychiatric ward is actually kind of nice?",
    "have an approachable aura?",
    "have a hard time letting go of people from their past. Especially close friends or ex lovers?",
    "enjoy staying away from your partner on a regular basis?",
    "find it HARDER to lock in without distractions nearby?",
    "not emotionally feel genuine concern/nervousness about anything?",
    "immediately walk naked when they’re find out they’re home alone?",
    "get worse at everything they do?",
    "feel an odd sense of relief at the thought that the one thing important to them getting taken away?",
    "feel like their face (specifically upper cheeks) are heavier when they’re tired?",
    "get really good ideas as they go to bed forget to tell anybody and immediately start doing them the next day?",
    "Get Kind Of Freaked Out That Color Isn\'t Real?",
    "notice that every nostalgic memory has its own kind of unique flavor or feeling of nostalgia almost like a mental smell?",
    "hate mustard but love honey mustard?",
    "love red pepper flakes but don’t like spicy sauces?",
    "hate wasting money on stupid stuff .",
    "not exchange gifts with their partner?",
    "freak out thinking someone\'s following you, just to realize it was the echo of your own shoes?",
    "get really sad when they realize they’ve forgotten something/someone from their past?",
    "think people who aren’t mentally well shouldn’t play games like Telltale games where you need to make difficult choices with relationships with people?",
    "feel their stomach drop when they jump/fall from a high place in a video game?",
    "always have others thinking you have a crush on them?",
    "remember a video game about a character with a parsnip hat and blue clothes in a forest?",
    "not get a lot of phone calls?",
    "get annoyed by unsolicited advice?",
    "think ChatGPT is smarter than half the population, and it\'s the dumb half of the population that thinks o4 is better, and o5 flopped?",
    "get stalked a lot?",
    "spend way too long crafting a perfect opener — only to end up sending \"Hey\"?",
    "prefer their pillow warm?",
    "really have to poop after eating a bagel?",
    "type up comments, large or small, to a Reddit post or other comment, think about it for a bit, then just delete it completely and move on?",
    "hate dreaming?",
    "wish their gym was right next to a park",
    "feel almost fully convinced that we manifest our reality?",
    "get annoyed when someone they don\'t find attractive gets a crush on them?",
    "ever want to become a monk?",
    "have intrusive thoughts?",
    "feel like they have to poop when they smell coffee?",
    "proofread their texts before sending them and again after sending them?",
    "Get Annoyed At People Taking 3 Tissues Out at a Time?",
    "feel like they have wings?",
    "not have a joint bank account with their spouse",
    "not like cold cheese but likes it melted?",
    "notice the later they put off going to bed, the harder it is to actually fall asleep?",
    "roll a slice of pizza so the crust mixes with the cheese and sauce, because otherwise the crust by itself is too boring?",
    "feel uncomfortable with the concept of eating?",
    "absolutely love eating watermelon seeds?",
    "experience uncomfortable sensation in their stomach laying flat on hard surface?",
    "get ready to blast someone because of their stupid comment, but you go look at their profile and decide to cut them some slack after getting to know a bit about them?",
    "struggle with depression, and family use to seeing you depressed, but sometimes you get so high that you\'re now happy but you pretend to still be sad for a brief moment until you walk past them?",
    "get freaked out by those cgi monkey films/games?",
    "have envy over people with a certain hair color?",
    "feel irritated after drinking soda?",
    "miss being rewarded for being potty trained?",
    "overthink strokes of luck?",
    "get kinda tired of breathing? Not in a suicidal way but in a \"Wow I can\'t believe I have to keep doing this\" way?",
    "think ice cream kinda just lasted forever?",
    "like eating food while walking the streets?",
    "feel like you were not cool enough for the cool kids and not nerdy enough for the nerds in high school and kinda just floated around friend groups?",
    "want kids but don\'t want the hassle that comes with it?",
    "use more toilet paper that necessary when using the toilet",
    "always have a song in their head?",
    "is having a pretty boring summer ?",
    "want to be the opposite gender but they\'re not trans?",
    "get the urge to scratch the inner part of your elbows sometimes. Soothing as well",
    "have their finger nails/nail beds go numb and tingly when they have to poop???",
    "after they shower squeegee off the excess water with their hands so the towel doesn\'t get too wet?",
    "swallow or gulp every few seconds for no reason at all?",
    "Does anyone else actively enjoy being a courteous driver?",
    "have dreams about being back in school?",
    "hate the feeling of air on them ?",
    "kind of cringe half the time people say \"Oh I was uncomfortable with ____\"",
    "find it annoying that every app has an AI chatbot nowadays?",
    "always get small injuries",
    "not feel the affect of coffee ?",
    "brain not work right when they have a headache",
    "get mildly depressed when a store selling important products you need goes out of business and is replaced with a shiddy Halloween store?",
    "hate being content so they force themselves to be miserable anytime they feel like everything can be ok again?",
    "want to get the deepest farmers tan/tee shirt tan they can to show they are outdoors a lot?",
    "occasionally lose the “human filter”",
    "really like doing something you probably ought not, for reasons of physical safety, while tripping?",
    "have “friends” who ridicule you for caring about social, political, economic etc issues?",
    "put on different \"masks\" when dealing with different people?",
    "with some sense of religion feel reluctant to pray for themselves?",
    "need to fully understand a system before participating in that system?",
    "find long, pointy (fang-like) canine teeth on people to be attractive/hot?",
    "struggle w codependency?",
    "hate when people use the word “flavor” when discussing scent?",
    "feel like their being watched at night?",
    "find that milk tastes spoiled for them a day or two before it does for other people?",
    "Not get vaxxed during the pandemic out of avoidance of crowds",
    "lose the ability to feel fear when on lexipro?",
    "wonder how (unpaid?) background extras in TV shows act normal?",
    "make ice cream cones for themselves at home?",
    "feel too lazy or not cut out for life?",
    "stay up till midnight to do puzzles when they are posted, then you don\'t go to bed until 2 or 3am?",
    "is getting so tired with the \"Nothing beats a jet 2 holiday\" meme??",
    "get paranoid that someone is watching them",
    "get annoyed when the toilet paper roll isnt a cylinder anymore?",
    "find that their patience for rude nasty people is almost to the point that you want to be rude and nasty too them.",
    "just block everything and everyone they never want to be exposed to again?",
    "have an ACTUAL fear of women",
    "enjoy incognito bike access but lose motivation when it was no longer incognito",
    "uncontrollably smile when they see an attractive person walking down the street?",
    "sing out loud around the house doing tasks, and when the task isn\'t going well, repeat the part you are singing as if a record is skipping?",
    "put off completing media? (tv, podcasts, etc)",
    "find it weird how many files you probably appear in where no one knows who you are?",
    "feel like flies in your house makes it seem unclean?",
    "hate that gyms are necessary ?",
    "loathe their software remote job but cant afford to leave bc of the pay",
    "get an unknown emotion in their stomach seemingly randomly?",
    "not want their pets to sleep with them?",
    "neurodivergent or with mental illness feel bad about needing medication to be “normal”?",
    "feel a kind of physical euphoria after they take a really big poo?",
    "notice all the little bugs on the road when you’re driving",
    "get restless from staying in all day?",
    "regret being adult?",
    "wonder what the world looks like from the perspective of someone who’s never had social media?",
    "feel like all they exist for is to satisfy other people\'s loneliness?",
    "get annoyed by people who are always late?",
    "wish parents would stop being overprotective?",
    "hear your own name in your brain very clearly to the point you have to glance around to see if someone actually said your name?",
    "feel upset or frustrated when people don\'t respond to messages?",
    "get an unknown emotion in their stomach for seemingly no reason?",
    "feel extremely validated when the comment they planned to make is already the top comment of a post?",
    "feel fine on their body with no physical pain but you still feel like there\'s sharp or gripping pain all over your body that you have to flex and bend your body to relieve it.",
    "roll their eyes without realizing/meaning to? If so how do you deal with the aftermath?",
    "feel weird talking to minors",
    "stop having interests after turning adult?",
    "feel like they don\'t exist?",
    "tear up easily when they get emotional?",
    "not mind spoilers?",
    "have violent goosebumps? Like spasms or tics",
    "feel like no matter what you do, say or behave. You\'re seen as the bad guy?",
    "view their taken friends as so far off the table they’re practically siblings/gay/etc?",
    "get put off by the person you’re dating pretending not to know you in front of other people?",
    "not feel strongly about anything",
    "wonder how tribes with little to no contact with the outside world reacted to seeing Sputnik orbit the earth in the late 1950s?",
    "randomly get apathetic of everything?",
    "get the urge to bite people’s long nails?",
    "just look at nature in awe and wonder?",
    "lose time?",
    "think & feel super deeply and are constantly analyzing the world and people around you while your SO is not, and has very little feedback or contribution when it comes to deeper topics of conversation?",
    "have to burst out laughing when happy or joyful?",
    "just absolutely love the feeling of finally peeing after holding your bladder for too long?",
    "feel really uncomfortable being called “boss?”",
    "dislike blue and green being together?",
    "feel an incredibly strong urge to travel abroad sometimes?",
    "respond with sarcasm to questions in a way that overlook the obvious?",
    "hate wasting food to the point they\'ll give their leftovers to a homeless person?",
    "have(or had) a friend you only refer to by their nickname?",
    "remember a school activity consisting of gathering in the gym (or similar) for a large group counseling session, sitting in circles, talking about serious topics, and crying?",
    "hate it when people refuse to watch movie/show trailers",
    "not like too many chocolate chips in their cookie?",
    "kind of look forward to dying just to finally satisfy their curiosity and see whats behind the curtain?",
    "dislike the sensation of the sound source being inside your head when listening to music through headphones/earbuds?",
    "find cheating in fiction extremely triggering?",
    "have trouble understanding monotone voices?",
    "annoy themselves by talking to themselves",
    "feel awkward when they encounter some they remember, but the other person doesn’t remember THEM?",
    "remember an old meme at 3am and wind up cackling at such a high pitch you might as well grab a broomstick and fly?",
    "always have felt like they\'re the opposite gender?",
    "get \"last day depression\" for things like events or deliveries?",
    "have very vivid, memorable dreams that often follow their own continuity?",
    "not slow down their pace when walking/speed walking towards upcoming obstacles in their path and just quickly move/dodge with their body to fit the shape of the space left next to the obstacle?",
    "regularly listen to video game OSTs? If so what game?",
    "ignore the use by dates on food packaging.",
    "get nauseous from fast/restaurant food?",
    "feel pain/discomfort from straps resting on your collarbone?",
    "hesitate to watch the last few episodes of a series because you’ll think “well, it’s over. What do I do now?”",
    "think drunk drivers should be banned from driving for life?",
    "get bothered by stuff smelling like someone else’s house",
    "get paranoid that people know who you are in anonymous online spaces?",
    "feel like when they go on a trip the locals feel like have the same personality and looks",
    "just feel “off” in social settings?",
    "get physical reactions or pace their house when they get in an online argument?",
    "pretend to play phone to cover up embarrassment in socializing?",
    "have nightmares when they sleep on their back?",
    "ever lay up at night thinking about all the times people that have wronged you?",
    "have dreams where you trip or fall and when you are about to hit the floor you wake up right when you are about to go to sleep",
    "look at old school photos of random cute pets and get sad they aren\'t alive or is it just me?",
    "not frequently use paper towels or dryers after washing their hands",
    "not care about customizing emojis",
    "worry brain chips will create a workplace environment of favoring AI dependent drone ppl",
    "imagine they\'re going to get shot, especially while driving?",
    "like when things are really salty?",
    "get bothered with the “that’s human nature” excuse?",
    "get the feeling they don\'t know whether they need to pee or not?",
    "ache from alcohol",
    "feel like people are funnier now?",
    "wear their pajamas with the shirt tucked in?",
    "not get hungry at all when you’re too busy at work ?",
    "not have a type?",
    "anybody else find more of the opposite sex to be appealing as you age?",
    "think people on LinkedIn are full of bullshit?",
    "find different months have different smells",
    "like extreme weather, like storms?",
    "upvote everyone that responds to their post and upvote every post they respond to?",
    "like looking at their face a lot",
    "have a fear and/or intrusive thoughts about pressing the emergency button on their phone?",
    "Used to Believe in Bloody Mary as a Child?",
    "look up words they don\'t know while reading?",
    "feel silly for getting jealous of kids getting to do things they never got to do?",
    "dislike seeing slave owners on their currency (if applicable)?",
    "wish they could hang their arms up at night?",
    "have the weird perception of height, vertically and horizontally?",
    "doesn\'t display any photos of real people at home?",
    "remember the spongmonkies?",
    "hate when you are about to talk to a girl that you are interested in and then her friends happen to pop up out of nowhere and start talking to her?",
    "feel like it\'s creepy to focus on a single background dancer during a live concert?",
    "wear scuba goggles when chopping onions?",
    "get bored when a relationship is flowing perfectly?",
    "like the feel of silicone?",
    "kind of hate birthdays?",
    "gets a sudden urge to feel the veins in their arms",
    "think crocs are trash?",
    "not realize that \"The Beatles\" is a pun on \"beat\", despite being an adult musician/person who knows a lot about music",
    "think MCU is trying too hard to “one-up” its previous villains? (spoilers for Thunderbolts and Fantastic 4)",
    "after watching a really good show, feel like the only sensible response is to stand on top of their desk and piss straight into the air out of joy?",
    "have distant acquaintances on socials that you only keep for the drama?",
    "get really scared and start crying when someone (they trust) stops and just stares at them with wide eyes?",
    "don\'t understand why people keep smoking tobacco?",
    "wonder why servers and cashiers ask you (the customer) how your day is going?",
    "think it’s not appropriate to bring children to bars?",
    "Smell Powdery/Pleasant When There\'s Nothing There.",
    "put their blanket in the dryer for a few minutes before bed?",
    "have a swirly belly button?",
    "follow odd or strange YouTube channels with hardly any followers?",
    "think of Milky Way candy bars every time they hear the word “Milwaukee”?",
    "dislike the phrase \"dive bar\"?",
    "not understand when people say they work in “corporate” or “consulting”",
    "enjoy the feeling after a good shave?",
    "hate the phrase “nook and cranny”",
    "prefer to dip things rather than spread them?",
    "put cream cheese on their pancakes?",
    "prefer a firm mattress?",
    "feel satisfied when people upvote their true facts?",
    "randomly remember repressed stuff from their childhood?",
    "think that feeling the need to upgrade your iPhone every year is more of a status symbol than anything else?",
    "wonder what clay tastes like?",
    "find it annoying whenever you have any kind of service done , they will not stop hounding you until you leave a Google review?",
    "Really love only one book series from an author?",
    "just find it weird that you, others and objects exist?",
    "Get really bad goosebumps when holding a laugh or when laughing ?",
    "notice pimples on your body are really painful to pop vs pimples on your face?",
    "eat a big meal and then leave a tiny bit left",
    "shiver when they’re not cold sometimes?",
    "set alarms just to go back to sleep?",
    "Always wake up one or two mins before the alarm goes off?",
    "play ear crucifying sounds like nails on a chalkboard to stay awake",
    "not really care about dead celebrities and feel like they\'re over-glorified?",
    "like rubbing their feet together?",
    "feel like they need to stop caring and stop standing up for things to improve their well-being?",
    "have the ability to willfully dislocate their shoulder on command?",
    "have any qualities they were born with that other people just seem to hate",
    "feel pained that they wont see the vast majority of history and the future",
    "get weirdly attracted to optometrists?",
    "switch first letters because it sounds better?",
    "hate lying but also hate telling the truth?",
    "read words backwards all the time? Not in a dyslexic way",
    "think random, empty Finstas that follow you are the crushes you follow via your own Finsta?",
    "never listen to a song on the radio while you\'re driving? I started listening to talk radio and podcasts several years ago and could not tell you the last time I listened to a song or artist on the radio, unless it was an ad or tv commercial. I don\'t even have anytracks downloaded to the phone.",
    "change their underwear multiple times a day?",
    "usually dislike the bridge of a song?",
    "drink a lot of caffeine before going out just to be more outgoing and social ?",
    "think pictures of people just looking straight at the camera and smiling is creepy",
    "feel like they’re “assholes” when encountering bad drivers or pedestrians unaware of their surroundings?",
    "have disruptive \"glitches\" or abnormalities in their internal monologue/imagination?",
    "struggle to enjoy things “catered for their gender”?",
    "see a post roughly a month and a half ago that someone was predicating a major earthquake near Japan and warning people not to go there?",
    "still close the bathroom door even if they\'re the only person in the house?",
    "get sad about stores not having a lot of customers?",
    "not drink water",
    "Hate airports?",
    "desperately wish they didn’t have a smartphone?",
    "struggle with word usage and spelling often?",
    "listen to music in full album format?",
    "have the urge to climb one of the highest mountains in the world?",
    "not get full with a Big Mac meal !!??",
    "feel like the expense of standing in a wedding should be on the wedding couple?",
    "get frustrated with people who are slow to complete tasks?",
    "wish Netflix and other streaming services had a comment section?",
    "struggle with seasonal depression in the summer?",
    "feel the existential pang of guilt for spending too much time on the internet and how much time you\'ve wasted, but then also feel the angst of feeling guilty for resting or enjoying leisure at all?",
    "feels extremely bored at home, but don\'t feel like doing anything either???",
    "feel like they observe human relationships from the outside?",
    "really enjoy the very early morning?",
    "agree that twitch is quicker to ban a streamer if they’re a male, vs a female?",
    "ever swallow wrong and get food stuck in their nose?!",
    "parents yell when you have music in your room?",
    "feel like taking someone out on their birthday is gift enough?",
    "brush their teeth when they\'re depressed",
    "cut up their buttermilk biscuits into bite size pieces before adding gravy?",
    "rewatch the same movies/TV over and over?",
    "have a mirror that makes them look better than anything else?",
    "think potential murders watch/listen to true crime to try and find ways to avoid getting caught?",
    "deal with unwelcomed rude comments or replies?",
    "microwave their pint of ice cream?",
    "enjoy listening to sad music when they are not sad",
    "NEED to know what direction (N/E/S/W) they are facing?",
    "To farm a colony of mealworms to have a sustainable source of protein.",
    "like to use pens entirely before u buy new ones?",
    "always regret opening canned drinks after taking the first sip?",
    "feel happier (have better mental health) in the cold months?",
    "call the end slices of the bread loaf \"donkey bread\"?",
    "feel disconnected from everyone?",
    "not get the whole spicy-love thing that it seems everyone has?",
    "mentally checkout because of certain words/phrases?",
    "get weirded out when they’re watching a movie with someone bc it relates to something going on between you and the person",
    "love stereotypically girly stuff?",
    "catch something before they’ve processed that it has fallen?",
    "not know what their mental diagnosis is?",
    "stop to sniff and smell paper money bills",
    "have a thing that\'s generally known as a problem but it is not a problem in the slightest?",
    "write and eat with one hand but do everything else with their left hand?",
    "find a person disproportionately annoying when they use flowery, needlessly ornate language in normal communication?",
    "watch disaster movies (alien, apocalypse natural) and wonder - what would Trump do (WWTD) ?",
    "get time related words confused?",
    "just not enjoy travelling in their own country?",
    "feel embarrassed by what they enjoy doing?",
    "checks user profile before replying or commenting on a post?",
    "Just not give a shit about Celeb couples/families?",
    "feel like they fake human interactions?",
    "feel grumpy all the time because of how much inflation has increased prices?",
    "pour themselves a cup of coffee and forget about it?",
    "hate the smell of red meat/poultry?",
    "WANT a partner who loves video games?",
    "wish they could drink or smoke as much as they want without health repercussions?",
    "unsure if they want kids because the thought of how much you will love them is almost unbearable?",
    "experience psychotic symptoms when quitting smoking?",
    "write $ with two lines?",
    "think that due to spam/scams, email has been destroyed as a reliable form of communication?",
    "feel like their youth was a completely different person? Like it wasn\'t actually \"you\" who lived it?",
    "get anxious when around authority figures?",
    "when got tattoos it feel like electricity is going though you when you got them when they doing it",
    "hold their breath as they pass people?",
    "like to always know what time it is?",
    "openly tell their friends that they appreciate their friendship?",
    "like to meditate on the dialog and plot of movies from the 90\'s and think about all they ways they\'re elaborate double/triple-cross indoctrination mechanisms?",
    "freak out if someone else is putting eyeliner on you?",
    "enjoy drinking creamer?",
    "use “dude” or “bro” in a unisex way?",
    "break in high heels by cleaning the house in them?",
    "feel like living in this day and age makes it impossible to not be sick",
    "like watching scammers crash out when they get called out in comments?",
    "have an intense fear of automatic flushing toilets as a kid?",
    "find people wearing gloves attractive?",
    "look up the handbags you see women carrying on TV or movies.",
    "cry (or feel like crying) when sick?",
    "have bad allergies in Thrift/Antique stores",
    "feel like life is moving too slow",
    "Think We\'re Losing Basic Social Skills?",
    "gather dust piles while sweeping and imagine they’re little cities ?",
    "have someone you cut off return in dreams?",
    "sometimes check to see if you developed powers? I tried to will my phone to me so I didn’t have to get up.",
    "think “Camp Mystic” is a strange name for a Christian camp?",
    "get a weird, almost heavy feeling when consuming certain media?",
    "Screenshot text conversations to preserve great moments?",
    "hate when people walk in the street or in public places while staring down at their phone.",
    "miss the really rough times?",
    "often feel like a piece of yourself is missing, something indefinable, but it feels like you used to have it but now it\'s gone and life is colder and bleaker because of it?",
    "have a favorite piece of cutlery?",
    "dislike the texture of water directly on their skin",
    "feel like the advice we give others tends to be the advice we need to take ourselves?",
    "feel like a hypocrite for no reason?",
    "have type 🆎 blood?",
    "thrive in group conversations but completely awkward in one on ones?",
    "hate the feeling of touching frosted glass to the point of grimacing and sets your teeth on edge?",
    "get emotional when they experience nostalgia?",
    "find watching tv alone extremely lonely ?",
    "feel like they are getting more mentally ill as they age?",
    "face situations where you\'re required to give updates to people who don\'t want to be bothered?",
    "get upset when an old friend unfriends/unfollows you?",
    "like cleaning?",
    "notice that most of the organized protest posts have disappeared? Even my Facebook is different right now.",
    "carry their wallet in their bag instead of their pants pockets?",
    "have full on conversations with their pets?",
    "eat leftover lunch or supper for breakfast?",
    "get more annoyed by little and inconsistent noises than loud ones?",
    "think this sub’s name should be changed to WEOH (Who Else Out Here… ?)",
    "feel like summer doesn\'t feel like summer this year?",
    "hear an electric/buzzing sound in their head when you’re hungry?",
    "name their car? What’s the best name you’ve given your car?",
    "think you could live without social media for a year?",
    "have to poop shortly after smoking marijuana?",
    "not know what to say…ever??",
    "sometimes get super aware about the fact that they exist and then get super uncomfortable or am I just going insane?",
    "scared of flying?",
    "wanna throw their smart phone into the sea? 🤳💨🌊",
    "worry about suddenly dying and leaving chaos behind for their family?",
    "refer to their shoes as \"Feet prisons\"? I hate shoes and flip flops when I can.",
    "get very out of breath and lightheaded DURING eating?",
    "always feel really sad on the day of Christmas?",
    "feel like the bar for \"me time\" keeps shrinking as you get older ?",
    "remember when it was normal to invite friends over to do chores together?",
    "get numbness and/or tingling in their jaw or back of the throat when eating something really really good?",
    "Fill their tank when at half full?",
    "give their pets a middle name",
    "count your steps when walking on sidewalks or going up or down the stairs?",
    "get a weird sense of loss after finishing a really good to-do list, like you no longer know who you are without your tasks?",
    "save all the croutons on a salad to eat last?",
    "plant trees over their pet’s graves",
    "find it really difficult to get local info about your town using the internet?",
    "erase everything when upset?",
    "have to eat things in even numbers",
    "just not believe in anything supernatural? (Gods, demons, angels, ghosts, spirits, souls, fairies, etc)",
    "replace their feelings with buying stuff?",
    "wake up several times a night?",
    "just absolutely dread night time?",
    "think that all the posts on this sub are basically things that most people do?",
    "think chick-fil-a is overrated?",
    "dislike surprise or last-minute visits?",
    "find it impossible to do mental math?",
    "get emotionally hungover after a really deep conversation",
    "go through waves of deleting and re-downloading social media apps ?",
    "like words with an even number of letters much more than words with an odd number of letters?",
    "feel so super addicted to stimuli that they are endlessly exhausted with a noisy head?",
    "feel afraid of expressing opinions?",
    "just pee standing in the shower while bathing?",
    "get imposter syndrome about relationships?",
    "not want to survive the apocalypse?",
    "get annoyed by their own nose hair",
    "use chatgpt as therapy/a mirror and it reflects back that you are an oracle that can save the world?",
    "hate when someone uses your name while talking to you in conversation and not to just get your attention?",
    "think the smell of gasoline smells good?",
    "think every single thing you read on here is fake?",
    "use chores as a form of emotional regulation?",
    "Always find great parking everywhere they go?",
    "get weird dreams when they take melatonin?",
    "feel like they try to follow the rules of polite society and laws of our country?",
    "like to fall asleep in their glasses on purpose?",
    "get excited when you hear a song in public or online from a relatively unknown artist you enjoy?",
    "constantly get ads for communities that are obviously cults?",
    "abstain from social media because people act fake?",
    "have to take off all clothes when pooping?",
    "get the hiccups when they poop ?",
    "zone out when trying to read anything technical/jargon-y?",
    "not want friends?",
    "notice that Reddit, if untamed, will make every effort to make you feel insecure and indulge in primal, stupid nonsense?",
    "bite the skin around their nails?",
    "get sleepy on the drive home from work",
    "avoid touching the shower curtain?",
    "feel fine with having a professional, cordial relationship with their parents?"
];